package POJO;
// Generated 09/11/2014 13:16:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Acesso generated by hbm2java
 */
public class Acesso  implements java.io.Serializable {


     private Integer acessoCodigo;
     private String acessoUsuario;
     private String acessoSenha;
     private Set funcionarios = new HashSet(0);

    public Acesso() {
    }

    public Acesso(String acessoUsuario, String acessoSenha, Set funcionarios) {
       this.acessoUsuario = acessoUsuario;
       this.acessoSenha = acessoSenha;
       this.funcionarios = funcionarios;
    }
   
    public Integer getAcessoCodigo() {
        return this.acessoCodigo;
    }
    
    public void setAcessoCodigo(Integer acessoCodigo) {
        this.acessoCodigo = acessoCodigo;
    }
    public String getAcessoUsuario() {
        return this.acessoUsuario;
    }
    
    public void setAcessoUsuario(String acessoUsuario) {
        this.acessoUsuario = acessoUsuario;
    }
    public String getAcessoSenha() {
        return this.acessoSenha;
    }
    
    public void setAcessoSenha(String acessoSenha) {
        this.acessoSenha = acessoSenha;
    }
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }




}


