package POJO;
// Generated 21/11/2014 21:22:07 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Cargo generated by hbm2java
 */
public class Cargo  implements java.io.Serializable {


     private Integer cargoCodigo;
     private BigDecimal cargoSalario;
     private String cargoNome;
     private Set funcionarios = new HashSet(0);

    public Cargo() {
    }

    public Cargo(BigDecimal cargoSalario, String cargoNome, Set funcionarios) {
       this.cargoSalario = cargoSalario;
       this.cargoNome = cargoNome;
       this.funcionarios = funcionarios;
    }
   
    public Integer getCargoCodigo() {
        return this.cargoCodigo;
    }
    
    public void setCargoCodigo(Integer cargoCodigo) {
        this.cargoCodigo = cargoCodigo;
    }
    public BigDecimal getCargoSalario() {
        return this.cargoSalario;
    }
    
    public void setCargoSalario(BigDecimal cargoSalario) {
        this.cargoSalario = cargoSalario;
    }
    public String getCargoNome() {
        return this.cargoNome;
    }
    
    public void setCargoNome(String cargoNome) {
        this.cargoNome = cargoNome;
    }
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }




}


