package POJO;
// Generated 21/11/2014 21:22:07 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer clienteCodigo;
     private Pessoa pessoa;
     private Date clienteDataCadastro;
     private Set vendas = new HashSet(0);

    public Cliente() {
    }

    public Cliente(Pessoa pessoa, Date clienteDataCadastro, Set vendas) {
       this.pessoa = pessoa;
       this.clienteDataCadastro = clienteDataCadastro;
       this.vendas = vendas;
    }
   
    public Integer getClienteCodigo() {
        return this.clienteCodigo;
    }
    
    public void setClienteCodigo(Integer clienteCodigo) {
        this.clienteCodigo = clienteCodigo;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Date getClienteDataCadastro() {
        return this.clienteDataCadastro;
    }
    
    public void setClienteDataCadastro(Date clienteDataCadastro) {
        this.clienteDataCadastro = clienteDataCadastro;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }




}


