package POJO;
// Generated 09/11/2014 13:16:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Contato generated by hbm2java
 */
public class Contato  implements java.io.Serializable {


     private Integer contatoCodigo;
     private String contatoTelefone;
     private String contatoTelefoneAlternativo;
     private String contatoCelular;
     private String contatoEmail;
     private Set fornecedors = new HashSet(0);
     private Set pessoas = new HashSet(0);
     private Set unidades = new HashSet(0);

    public Contato() {
    }

    public Contato(String contatoTelefone, String contatoTelefoneAlternativo, String contatoCelular, String contatoEmail, Set fornecedors, Set pessoas, Set unidades) {
       this.contatoTelefone = contatoTelefone;
       this.contatoTelefoneAlternativo = contatoTelefoneAlternativo;
       this.contatoCelular = contatoCelular;
       this.contatoEmail = contatoEmail;
       this.fornecedors = fornecedors;
       this.pessoas = pessoas;
       this.unidades = unidades;
    }
   
    public Integer getContatoCodigo() {
        return this.contatoCodigo;
    }
    
    public void setContatoCodigo(Integer contatoCodigo) {
        this.contatoCodigo = contatoCodigo;
    }
    public String getContatoTelefone() {
        return this.contatoTelefone;
    }
    
    public void setContatoTelefone(String contatoTelefone) {
        this.contatoTelefone = contatoTelefone;
    }
    public String getContatoTelefoneAlternativo() {
        return this.contatoTelefoneAlternativo;
    }
    
    public void setContatoTelefoneAlternativo(String contatoTelefoneAlternativo) {
        this.contatoTelefoneAlternativo = contatoTelefoneAlternativo;
    }
    public String getContatoCelular() {
        return this.contatoCelular;
    }
    
    public void setContatoCelular(String contatoCelular) {
        this.contatoCelular = contatoCelular;
    }
    public String getContatoEmail() {
        return this.contatoEmail;
    }
    
    public void setContatoEmail(String contatoEmail) {
        this.contatoEmail = contatoEmail;
    }
    public Set getFornecedors() {
        return this.fornecedors;
    }
    
    public void setFornecedors(Set fornecedors) {
        this.fornecedors = fornecedors;
    }
    public Set getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Set pessoas) {
        this.pessoas = pessoas;
    }
    public Set getUnidades() {
        return this.unidades;
    }
    
    public void setUnidades(Set unidades) {
        this.unidades = unidades;
    }




}


