package POJO;
// Generated 21/11/2014 21:22:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estado generated by hbm2java
 */
public class Estado  implements java.io.Serializable {


     private Integer estadoCodigo;
     private String estadoNome;
     private String estadoSigla;
     private Set cidades = new HashSet(0);

    public Estado() {
    }

    public Estado(String estadoNome, String estadoSigla, Set cidades) {
       this.estadoNome = estadoNome;
       this.estadoSigla = estadoSigla;
       this.cidades = cidades;
    }
   
    public Integer getEstadoCodigo() {
        return this.estadoCodigo;
    }
    
    public void setEstadoCodigo(Integer estadoCodigo) {
        this.estadoCodigo = estadoCodigo;
    }
    public String getEstadoNome() {
        return this.estadoNome;
    }
    
    public void setEstadoNome(String estadoNome) {
        this.estadoNome = estadoNome;
    }
    public String getEstadoSigla() {
        return this.estadoSigla;
    }
    
    public void setEstadoSigla(String estadoSigla) {
        this.estadoSigla = estadoSigla;
    }
    public Set getCidades() {
        return this.cidades;
    }
    
    public void setCidades(Set cidades) {
        this.cidades = cidades;
    }




}


