package POJO;
// Generated 09/11/2014 13:16:52 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private Integer funcionarioCodigo;
     private Acesso acesso;
     private Cargo cargo;
     private Pessoa pessoa;
     private Unidade unidade;
     private Date funcionarioDataAdmissao;
     private Date funcionarioDataCadastro;
     private Set vendas = new HashSet(0);

    public Funcionario() {
    }

    public Funcionario(Acesso acesso, Cargo cargo, Pessoa pessoa, Unidade unidade, Date funcionarioDataAdmissao, Date funcionarioDataCadastro, Set vendas) {
       this.acesso = acesso;
       this.cargo = cargo;
       this.pessoa = pessoa;
       this.unidade = unidade;
       this.funcionarioDataAdmissao = funcionarioDataAdmissao;
       this.funcionarioDataCadastro = funcionarioDataCadastro;
       this.vendas = vendas;
    }
   
    public Integer getFuncionarioCodigo() {
        return this.funcionarioCodigo;
    }
    
    public void setFuncionarioCodigo(Integer funcionarioCodigo) {
        this.funcionarioCodigo = funcionarioCodigo;
    }
    public Acesso getAcesso() {
        return this.acesso;
    }
    
    public void setAcesso(Acesso acesso) {
        this.acesso = acesso;
    }
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Unidade getUnidade() {
        return this.unidade;
    }
    
    public void setUnidade(Unidade unidade) {
        this.unidade = unidade;
    }
    public Date getFuncionarioDataAdmissao() {
        return this.funcionarioDataAdmissao;
    }
    
    public void setFuncionarioDataAdmissao(Date funcionarioDataAdmissao) {
        this.funcionarioDataAdmissao = funcionarioDataAdmissao;
    }
    public Date getFuncionarioDataCadastro() {
        return this.funcionarioDataCadastro;
    }
    
    public void setFuncionarioDataCadastro(Date funcionarioDataCadastro) {
        this.funcionarioDataCadastro = funcionarioDataCadastro;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }




}


