package POJO;
// Generated 09/11/2014 13:16:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

/**
 * Marca generated by hbm2java
 */

public class Marca  implements java.io.Serializable {
    
     private Integer marcaCodigo;
     private String marcaNome;
     
     private Set produtos = new HashSet(0);
    
    public Marca() {
    }

    public Marca(String marcaNome, Set produtos) {
       this.marcaNome = marcaNome;
       this.produtos = produtos;
    }
   
    public Integer getMarcaCodigo() {
        return this.marcaCodigo;
    }
    
    public void setMarcaCodigo(Integer marcaCodigo) {
        this.marcaCodigo = marcaCodigo;
    }
    public String getMarcaNome() {
        return this.marcaNome;
    }
    
    public void setMarcaNome(String marcaNome) {
        this.marcaNome = marcaNome;
    }
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }
}


