package POJO;
// Generated 09/11/2014 13:16:52 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.OneToMany;

/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {

     private Integer produtoCodigo;
     private Fornecedor fornecedor;
     private Marca marca;
     private BigDecimal produtoPreco;
     private String produtoNome;
     private String produtoDescricao;
     private Integer produtoQuantidade;
     private Set produtoVendas = new HashSet(0);

    public Produto() {
    }

    public Produto(Fornecedor fornecedor, Marca marca, BigDecimal produtoPreco, String produtoNome, String produtoDescricao, Integer produtoQuantidade, Set produtoVendas) {
       this.fornecedor = fornecedor;
       this.marca = marca;
       this.produtoPreco = produtoPreco;
       this.produtoNome = produtoNome;
       this.produtoDescricao = produtoDescricao;
       this.produtoQuantidade = produtoQuantidade;
       this.produtoVendas = produtoVendas;
    }
   
    public Integer getProdutoCodigo() {
        return this.produtoCodigo;
    }
    
    public void setProdutoCodigo(Integer produtoCodigo) {
        this.produtoCodigo = produtoCodigo;
    }
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public BigDecimal getProdutoPreco() {
        return this.produtoPreco;
    }
    
    public void setProdutoPreco(BigDecimal produtoPreco) {
        this.produtoPreco = produtoPreco;
    }
    public String getProdutoNome() {
        return this.produtoNome;
    }
    
    public void setProdutoNome(String produtoNome) {
        this.produtoNome = produtoNome;
    }
    public String getProdutoDescricao() {
        return this.produtoDescricao;
    }
    
    public void setProdutoDescricao(String produtoDescricao) {
        this.produtoDescricao = produtoDescricao;
    }
    public Integer getProdutoQuantidade() {
        return this.produtoQuantidade;
    }
    
    public void setProdutoQuantidade(Integer produtoQuantidade) {
        this.produtoQuantidade = produtoQuantidade;
    }
    public Set getProdutoVendas() {
        return this.produtoVendas;
    }
    
    public void setProdutoVendas(Set produtoVendas) {
        this.produtoVendas = produtoVendas;
    }




}


