package POJO;
// Generated 09/11/2014 13:16:52 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ProdutoVenda generated by hbm2java
 */
public class ProdutoVenda  implements java.io.Serializable {


     private Integer produtovendaCodigo;
     private Produto produto;
     private Venda venda;
     private Integer produtovendaQuantidade;
     private BigDecimal produtovendaValorTotal;

    public ProdutoVenda() {
    }

    public ProdutoVenda(Produto produto, Venda venda, Integer produtovendaQuantidade, BigDecimal produtovendaValorTotal) {
       this.produto = produto;
       this.venda = venda;
       this.produtovendaQuantidade = produtovendaQuantidade;
       this.produtovendaValorTotal = produtovendaValorTotal;
    }
   
    public Integer getProdutovendaCodigo() {
        return this.produtovendaCodigo;
    }
    
    public void setProdutovendaCodigo(Integer produtovendaCodigo) {
        this.produtovendaCodigo = produtovendaCodigo;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Venda getVenda() {
        return this.venda;
    }
    
    public void setVenda(Venda venda) {
        this.venda = venda;
    }
    public Integer getProdutovendaQuantidade() {
        return this.produtovendaQuantidade;
    }
    
    public void setProdutovendaQuantidade(Integer produtovendaQuantidade) {
        this.produtovendaQuantidade = produtovendaQuantidade;
    }
    public BigDecimal getProdutovendaValorTotal() {
        return this.produtovendaValorTotal;
    }
    
    public void setProdutovendaValorTotal(BigDecimal produtovendaValorTotal) {
        this.produtovendaValorTotal = produtovendaValorTotal;
    }




}


