package POJO;
// Generated 09/11/2014 13:16:52 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venda generated by hbm2java
 */
public class Venda  implements java.io.Serializable {


     private Integer vendaCodigo;
     private Cliente cliente;
     private Funcionario funcionario;
     private Unidade unidade;
     private Date vendaData;
     private BigDecimal vendaValorTotal;
     private String vendaFormaPagamento;
     private Set produtoVendas = new HashSet(0);

    public Venda() {
    }

    public Venda(Cliente cliente, Funcionario funcionario, Unidade unidade, Date vendaData, BigDecimal vendaValorTotal, String vendaFormaPagamento, Set produtoVendas) {
       this.cliente = cliente;
       this.funcionario = funcionario;
       this.unidade = unidade;
       this.vendaData = vendaData;
       this.vendaValorTotal = vendaValorTotal;
       this.vendaFormaPagamento = vendaFormaPagamento;
       this.produtoVendas = produtoVendas;
    }
   
    public Integer getVendaCodigo() {
        return this.vendaCodigo;
    }
    
    public void setVendaCodigo(Integer vendaCodigo) {
        this.vendaCodigo = vendaCodigo;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Unidade getUnidade() {
        return this.unidade;
    }
    
    public void setUnidade(Unidade unidade) {
        this.unidade = unidade;
    }
    public Date getVendaData() {
        return this.vendaData;
    }
    
    public void setVendaData(Date vendaData) {
        this.vendaData = vendaData;
    }
    public BigDecimal getVendaValorTotal() {
        return this.vendaValorTotal;
    }
    
    public void setVendaValorTotal(BigDecimal vendaValorTotal) {
        this.vendaValorTotal = vendaValorTotal;
    }
    public String getVendaFormaPagamento() {
        return this.vendaFormaPagamento;
    }
    
    public void setVendaFormaPagamento(String vendaFormaPagamento) {
        this.vendaFormaPagamento = vendaFormaPagamento;
    }
    public Set getProdutoVendas() {
        return this.produtoVendas;
    }
    
    public void setProdutoVendas(Set produtoVendas) {
        this.produtoVendas = produtoVendas;
    }




}


